# Generated by Django 3.1 on 2021-03-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('money', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Желаемая зарплата')),
                ('about_me', models.TextField(verbose_name='О себе')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало работы')),
                ('end_date', models.DateField(verbose_name='Конец работы')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
        migrations.CreateModel(
            name='Soft_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(verbose_name='Дополнительные навыки')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на проекты')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на фото')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.JSONField(verbose_name='Мои хобби')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
        migrations.CreateModel(
            name='Hard_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(verbose_name='Основные навыки')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало учёбы')),
                ('end_date', models.DateField(verbose_name='Окончание учёбы')),
                ('university', models.CharField(max_length=255, verbose_name='Компания')),
                ('academy', models.CharField(max_length=255, verbose_name='Степень')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_resume.worker', verbose_name='Для работника')),
            ],
        ),
    ]
