# Generated by Django 3.1 on 2021-03-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='hard_skills',
            options={'verbose_name': 'Hard skill', 'verbose_name_plural': 'Hard skills'},
        ),
        migrations.AlterModelOptions(
            name='hobbie',
            options={'verbose_name': 'Хобби', 'verbose_name_plural': 'Хобби'},
        ),
        migrations.AlterModelOptions(
            name='photo_worker',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='soft_skills',
            options={'verbose_name': 'Soft skill', 'verbose_name_plural': 'Soft skills'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AddField(
            model_name='hard_skills',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hard skills'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Желаемая должность'),
        ),
    ]
