# Generated by Django 3.1 on 2021-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0002_auto_20210313_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=255, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='hard_skills',
            name='skills',
            field=models.CharField(max_length=255, verbose_name='Основные навыки'),
        ),
    ]
